# PROCESADO DATOS

### Importamos y leemos csvs

In [5]:
import pandas as pd

pd.set_option('display.max_rows', 1000)

In [6]:
df_da_or = pd.read_csv('info_data_analyst.csv')
df_ds_or = pd.read_csv('info_data_scientist.csv')

In [55]:
df_da = df_da_or[:500]
df_ds = df_ds_or[:500]

### LIMPIEZA DATAFRAMES

Columnas a limpiar:

- Ver si hay na:
    ```
    lista_na = []
    for i in list(df_da.columns):
        lista_na.append(df_da[i].isnull().values.any())
    ```
0. Nombre empresa: ok
    
    
1. Puesto ofertado: limpiar na
    ```
    pd.Series(' '.join(mask1).lower().split()).value_counts()[:300]
    ```
    
    
2. Ubicación: Dejar solo la primera palabra y limpiar na.
    ```
    df_da3['Sector'].str.split(' ').str[0]
    df = df['Ubicación'].str.replace(',', '')
    
    df.value_counts()
    ```

3. Días activos: eliminar 'Publicado hace hace' y contar horas semanas y días.
    ```
    df_da['Días activos'].str.replace('Publicado hace hace', '')
    
    df_da_p2['Días activos'] = df_da_p2['Días activos'].str.replace('Publicado hace hace', '')
    
    df_da_p2['Días activos'].value_counts()
    ```


4. Nº Solicitudes: eliminar 'visualizaciones' y revisar cuales tienen más visualizaciones.
    ```
    df_da_p2['Nº Solicitudes'] = df_da_p2['Nº Solicitudes'].str.replace(' visualizaciones', '') # También visualización y .
        
    df_da_p2['Nº Solicitudes'] = df_da_p2['Nº Solicitudes'].apply(lambda x: int(x))
    
    df_da_p2['Nº Solicitudes'].sort_values(ascending = False)
    ```

5. Nivel experiencia: eliminar errores y contar cada uno.
    ```
    mask7 = df_da[(df_da['Nivel experiencia'] == 'Sin experiencia') | (df_da['Nivel experiencia'] == 'Algo de responsabilidad') | (df_da['Nivel experiencia'] == 'Intermedio') | (df_da['Nivel experiencia'] == 'Prácticas')]
    
    mask7.groupby('Nivel experiencia')[['Puesto ofertado']].count()
    ```
    Probar `df[df["A"].str.contains("Hello|Britain")`


6. Sector: buscar las 4 primeras palabras de cada uno y agruparlas.
    ```
    pd.Series(' '.join(df_da3["Sector"]).lower().split()).value_counts()[:100]
    
    df_da4.filter(items=['data', 'experience'])
    `````

7. Tipo jornada: hacer un group by y contar.
    ```
    df_da3.groupby('Tipo jornada')['Nombre empresa'].count()
    ```


8. Funciones laborales: agrupar y contar palabras

9. Descripción : agrupar y contar palabras

In [56]:
df_da.head(2)

,Nombre empresa,Puesto ofertado,Ubicación,Días activos,Nº Solicitudes,Nivel experiencia,Sector,Tipo jornada,Funciones laborales,Descripción
0,Amazon,Junior Data Analyst,"Barcelona, Cataluña, España",Publicado hace hace 6 horas,66 visualizaciones,Sin experiencia,Software Servicios y tecnologías de la informa...,Jornada completa,Estrategia/planificación Análisis Tecnología d...,Description\n\nJunior Data Analyst\nWe are hir...
1,Packlink.com,Business Data Analyst,"Madrid, Comunidad de Madrid, España",Publicado hace hace 1 semana,638 visualizaciones,Intermedio,Servicios y tecnologías de la información Logí...,Jornada completa,Negocios Tecnología de la información Análisis,Do you want to be a part of a fast-paced compa...

## Tratamiento datos info_da

#### Limpiar nas:

In [133]:
lista_nas = []

for i in list(df_da.columns):
    lista_nas.append(df_da[i].isnull().values.any())
    

lista_col_nas = []

for i in range(len(lista_nas)):
    if lista_nas[i] == True:
        lista_col_nas.append(df_da.columns[i])

In [134]:
lista_col_nas

['Ubicación', 'Días activos', 'Nº Solicitudes', 'Nivel experiencia']

In [ ]:
df_da['Puesto ofertado'].fillna('no_data', inplace=True)

In [ ]:
df_da['Ubicación'].fillna('no_data', inplace=True)

In [138]:
df_da['Días activos'].fillna('no_data', inplace=True)

In [ ]:
df_da['Nº Solicitudes'].fillna(0, inplace=True)

In [144]:
df_da['Nivel experiencia'].fillna('no_data', inplace=True)

## Limpiar datos columnas:

#### Ubicación:

In [ ]:
df_da['Ubicación'] = df_da['Ubicación'].str.split(' ').str[0]

In [ ]:
df_da['Ubicación'] = df_da['Ubicación'].str.replace(',', '')

#### Días activos:

In [ ]:
df_da['Días activos'] = df_da['Días activos'].str.replace('Publicado hace hace', '')

#### Solicitudes:

In [ ]:
lista_rem_so = [' visualizaciones', ' visualización', '.']

for i in lista_rem_so:
    df_da['Nº Solicitudes'] = df_da['Nº Solicitudes'].str.replace(i, '')

In [ ]:
df_da['Nº Solicitudes'] = df_da['Nº Solicitudes'].astype(int)

In [175]:
df_da['Nº Solicitudes'].head()

0      66
1     638
2    3490
3    3374
4    1122
Name: Nº Solicitudes, dtype: int64

#### Nivel experiencia:

In [186]:
mask_nexp = df_da['Nivel experiencia'].str.contains('Sin experiencia|Algo de responsabilidad|Intermedio|Prácticas')

In [187]:
mask_nexp

0       True
1       True
2       True
3       True
4       True
5       True
6       True
7       True
8       True
9       True
10      True
11      True
12      True
13      True
14      True
15      True
16      True
17     False
18      True
19      True
20      True
21      True
22      True
23     False
24      True
25      True
26      True
27      True
28     False
29      True
30      True
31      True
32      True
33      True
34     False
35      True
36      True
37      True
38      True
39      True
40      True
41      True
42     False
43      True
44      True
45      True
46      True
47      True
48      True
49      True
50      True
51      True
52      True
53      True
54      True
55      True
56      True
57      True
58      True
59      True
60      True
61      True
62      True
63      True
64      True
65      True
66      True
67      True
68      True
69      True
70      True
71      True
72      True
73      True
74      True
75     False
76     False
77     False
78      True
79      True
80      True
81      True
82      True
83      True
84      True
85      True
86      True
87      True
88      True
89      True
90      True
91      True
92      True
93      True
94      True
95      True
96      True
97      True
98      True
99      True
100    False
101     True
102     True
103     True
104     True
105     True
106     True
107     True
108     True
109     True
110     True
111     True
112     True
113     True
114     True
115    False
116     True
117     True
118     True
119     True
120     True
121     True
122    False
123     True
124     True
125    False
126    False
127     True
128     True
129     True
130     True
131     True
132     True
133     True
134     True
135    False
136    False
137     True
138     True
139     True
140     True
141     True
142     True
143     True
144     True
145     True
146     True
147    False
148     True
149     True
150     True
151     True
152     True
153     True
154     True
155    False
156     True
157     True
158     True
159    False
160     True
161     True
162     True
163    False
164     True
165     True
166     True
167     True
168     True
169     True
170     True
171     True
172     True
173     True
174     True
175     True
176     True
177     True
178    False
179     True
180     True
181     True
182     True
183     True
184     True
185    False
186     True
187     True
188     True
189     True
190     True
191     True
192     True
193     True
194     True
195     True
196     True
197     True
198     True
199    False
200     True
201     True
202     True
203     True
204     True
205     True
206     True
207     True
208    False
209     True
210     True
211     True
212     True
213     True
214     True
215    False
216     True
217     True
218     True
219     True
220    False
221     True
222     True
223     True
224     True
225     True
226     True
227     True
228     True
229     True
230     True
231    False
232     True
233     True
234     True
235     True
236     True
237     True
238     True
239    False
240     True
241     True
242     True
243     True
244    False
245     True
246     True
247     True
248    False
249     True
250     True
251     True
252     True
253     True
254     True
255     True
256     True
257    False
258     True
259     True
260    False
261     True
262     True
263     True
264    False
265     True
266     True
267     True
268    False
269     True
270     True
271     True
272     True
273     True
274     True
275     True
276     True
277     True
278     True
279    False
280     True
281     True
282     True
283     True
284     True
285     True
286     True
287     True
288    False
289     True
290     True
291     True
292     True
293    False
294     True
295     True
296     True
297     True
298     True
299     True
300    False
301     True
302    False
303     True
304     True
305     True
306     True
307     True
308     True
309     True
310     True
311     True
312     True
313     True
314    False
315     True
316     True
317     True
318     True
319     True
320     True
321     True
322     True
323    False
324     True
325     True
326     True
327     True
328     True
329     True
330     True
331     True
332     True
333     True
334     True
335    False
336     True
337     True
338     True
339     True
340     True
341     True
342    False
343     True
344     True
345     True
346     True
347    False
348     True
349     True
350     True
351    False
352     True
353     True
354     True
355     True
356    False
357     True
358     True
359     True
360    False
361     True
362     True
363     True
364    False
365     True
366     True
367     True
368     True
369     True
370     True
371     True
372     True
373     True
374     True
375     True
376    False
377     True
378     True
379     True
380     True
381     True
382     True
383     True
384     True
385     True
386     True
387    False
388     True
389     True
390     True
391    False
392     True
393     True
394    False
395    False
396    False
397     True
398     True
399     True
400     True
401    False
402     True
403    False
404    False
405     True
406    False
407     True
408     True
409     True
410    False
411     True
412    False
413     True
414     True
415     True
416     True
417     True
418     True
419    False
420    False
421     True
422     True
423     True
424     True
425     True
426     True
427     True
428     True
429    False
430     True
431     True
432     True
433     True
434     True
435    False
436    False
437     True
438     True
439     True
440     True
441    False
442     True
443     True
444     True
445    False
446     True
447     True
448     True
449    False
450     True
451     True
452    False
453    False
454    False
455     True
456    False
457     True
458     True
459     True
460    False
461     True
462     True
463     True
464     True
465     True
466     True
467     True
468    False
469     True
470     True
471     True
472     True
473     True
474     True
475     True
476     True
477     True
478    False
479     True
480     True
481     True
482     True
483     True
484     True
485     True
486     True
487     True
488     True
489     True
490    False
491     True
492     True
493     True
494     True
495     True
496     True
497     True
498     True
499     True
Name: Nivel experiencia, dtype: bool

In [ ]:
df_da.loc[-mask_nexp,'Nivel experiencia'] = 'no_data'

#### Tipo jornada

In [212]:
mask_tjor = df_da['Tipo jornada'].str.contains('Internet')

In [ ]:
df_da.loc[-mask_tjor,'Tipo jornada'] = 'no_data'

#### Guardado del fichero limpio

In [336]:
df_da.to_csv('info_data_analyst_clean.csv')

## Tratamiento datos info_ds

#### Limpiar nas:

In [215]:
lista_nas = []

for i in list(df_ds.columns):
    lista_nas.append(df_ds[i].isnull().values.any())

lista_col_nas = []

for i in range(len(lista_nas)):
    if lista_nas[i] == True:
        lista_col_nas.append(df_ds.columns[i])

In [216]:
lista_col_nas

['Puesto ofertado',
 'Ubicación',
 'Días activos',
 'Nº Solicitudes',
 'Nivel experiencia',
 'Sector',
 'Tipo jornada']

In [ ]:
df_ds['Puesto ofertado'].fillna('no_data', inplace=True)

In [218]:
df_ds['Ubicación'].fillna('no_data', inplace=True)

In [219]:
df_ds['Días activos'].fillna('no_data', inplace=True)

In [239]:
df_ds['Nº Solicitudes'].fillna(0, inplace=True)

In [221]:
df_ds['Nivel experiencia'].fillna('no_data', inplace=True)

In [222]:
df_ds['Sector'].fillna('no_data', inplace=True)

In [223]:
df_ds['Tipo jornada'].fillna('no_data', inplace=True)

## Limpiar datos columnas:

#### Ubicación:

In [230]:
df_ds['Ubicación']

0              Barcelona,
1              Barcelona,
2                 Madrid,
3               Barcelona
4            Palau-solità
5                 Madrid,
6              Barcelona,
7                 Madrid,
8                 Madrid,
9               Comunidad
10             Barcelona,
11                Madrid,
12                Madrid,
13     Valencia/València,
14                    San
15                Madrid,
16     Valencia/València,
17             Barcelona,
18                Madrid,
19                Madrid,
20                Madrid,
21                 España
22             Barcelona,
23             Barcelona,
24             Barcelona,
25                Madrid,
26                Madrid,
27                Madrid,
28                Madrid,
29             Barcelona,
30                Madrid,
31             Barcelona,
32                 Madrid
33              Zaragoza,
34                   Sant
35              Barcelona
36                Madrid,
37             Barcelona,
38             Barcelona,
39                Madrid,
40             Barcelona,
41           Donostia-San
42                Madrid,
43          Bilbao-Bilbo,
44             Barcelona,
45     Valencia/València,
46                no_data
47             Barcelona,
48                Madrid,
49             Barcelona,
50             Barcelona,
51              Canarias,
52                Madrid,
53                Madrid,
54           Donostia-San
55                    Las
56             Barcelona,
57             Barcelona,
58                Madrid,
59             Barcelona,
60                Madrid,
61                Madrid,
62             Barcelona,
63                Madrid,
64                 España
65     Valencia/València,
66                Madrid,
67                Madrid,
68     Valencia/València,
69                 Málaga
70                Madrid,
71             Barcelona,
72             Barcelona,
73             Barcelona,
74                Madrid,
75                Madrid,
76                Madrid,
77             Barcelona,
78                Madrid,
79             Barcelona,
80                Madrid,
81                     La
82                 España
83                Madrid,
84          Bilbao-Bilbo,
85                Málaga,
86                Madrid,
87                Málaga,
88                   Sant
89                no_data
90             Barcelona,
91                Madrid,
92                Madrid,
93                Madrid,
94                Madrid,
95             Barcelona,
96               Sevilla,
97                Madrid,
98                Madrid,
99     Valencia/València,
100                Madrid
101               Madrid,
102            Barcelona,
103            Barcelona,
104            Barcelona,
105    Valencia/València,
106               Madrid,
107               Madrid,
108            Barcelona,
109               Madrid,
110            Barcelona,
111               Madrid,
112               Madrid,
113            Barcelona,
114                Valls,
115               Madrid,
116            Barcelona,
117            Barcelona,
118            Barcelona,
119            Barcelona,
120               Madrid,
121            Barcelona,
122               Madrid,
123               Madrid,
124           Alcobendas,
125            Barcelona,
126               Madrid,
127            Barcelona,
128                 Nuevo
129               Pozuelo
130               Madrid,
131            Barcelona,
132         Bilbao-Bilbo,
133             Zaragoza,
134            Villanueva
135               Madrid,
136               Madrid,
137     Alicante/Alacant,
138            Barcelona,
139               Madrid,
140            Barcelona,
141               Madrid,
142                España
143            Barcelona,
144            Barcelona,
145                Bilbao
146            Barcelona,
147            Tarragona,
148            Barcelona,
149               Madrid,
150            Mondragón,
151               Madrid,
152              Almería,
153               Madrid,
154    Valencia/València,
155               Madrid,
156            Barcelona,
157        Navalagamella,
158               Madrid,
159              Cornellà
160               Madrid,
161            Barcelona,
162              Granada,
163            Barcelona,
164               Madrid,
165                Madrid
166            Barcelona,
167            Barcelona,
168                Madrid
169            Barcelona,
170               Málaga,
171                Madrid
172               Madrid,
173            Barcelona,
174              Sevilla,
175               Madrid,
176            Barcelona,
177            Barcelona,
178                  Sant
179            Barcelona,
180            Barcelona,
181               Madrid,
182          Donostia-San
183            Barcelona,
184             Comunidad
185                España
186            Barcelona,
187            Barcelona,
188            Barcelona,
189               Madrid,
190            Barcelona,
191            Barcelona,
192                España
193               Madrid,
194            Barcelona,
195            Barcelona,
196                  Sant
197           Sarriguren,
198               Madrid,
199            Barcelona,
200            Barcelona,
201               no_data
202                Madrid
203            Salamanca,
204            Barcelona,
205            Barcelona,
206            Barcelona,
207            Barcelona,
208            Barcelona,
209               Madrid,
210               Madrid,
211            Barcelona,
212              Sevilla,
213            Barcelona,
214               Madrid,
215            Barcelona,
216            Barcelona,
217            Barcelona,
218               Madrid,
219               Madrid,
220            Barcelona,
221     Alicante/Alacant,
222            Torrecilla
223            Barcelona,
224            Barcelona,
225              Granada,
226     Alicante/Alacant,
227               Madrid,
228               Madrid,
229               Madrid,
230              Sevilla,
231               Madrid,
232            Barcelona,
233               Madrid,
234               Lérida,
235               Madrid,
236            Torrecilla
237            Barcelona,
238         Bilbao-Bilbo,
239            Barcelona,
240            Barcelona,
241            Barcelona,
242            Barcelona,
243            Barcelona,
244            Barcelona,
245               Madrid,
246               Madrid,
247            Barcelona,
248            Barcelona,
249            Barcelona,
250            Barcelona,
251            Barcelona,
252               Madrid,
253               Madrid,
254               Madrid,
255            Barcelona,
256               Madrid,
257               Madrid,
258            Barcelona,
259               Madrid,
260            Andalucía,
261               Madrid,
262            Barcelona,
263               Madrid,
264    Valencia/València,
265            Barcelona,
266            Barcelona,
267                España
268            Barcelona,
269              Andorra,
270             Salamanca
271               Madrid,
272               Madrid,
273               Madrid,
274            Barcelona,
275               no_data
276            Barcelona,
277               Málaga,
278            Barcelona,
279                 Palma
280               Madrid,
281            Barcelona,
282            Barcelona,
283            Barcelona,
284               Pasaia,
285               Madrid,
286               Córdoba
287            Barcelona,
288               Madrid,
289    Valencia/València,
290            Barcelona,
291               Málaga,
292            Barcelona,
293            Barcelona,
294            Barcelona,
295            Salamanca,
296               Galicia
297            Barcelona,
298            Barcelona,
299                   San
300             Zaragoza,
301    Valencia/València,
302    Valencia/València,
303            Barcelona,
304           Arteaga-San
305            Barcelona,
306            Barcelona,
307               Madrid,
308          Donostia-San
309             Comunidad
310               Madrid,
311                    La
312            Barcelona,
313         Bilbao-Bilbo,
314             Canarias,
315              Cornellà
316            Barcelona,
317     Alicante/Alacant,
318            Barcelona,
319              Sevilla,
320               Galicia
321            Barcelona,
322                Caldes
323            Barcelona,
324            Barcelona,
325               Madrid,
326            Barcelona,
327            Barcelona,
328                  Sant
329            Barcelona,
330            Barcelona,
331              Sevilla,
332              Sevilla,
333               Madrid,
334               Madrid,
335            Torrecilla
336            Barcelona,
337               Madrid,
338            Barcelona,
339            Barcelona,
340                  Sant
341            Tarragona,
342            Barcelona,
343            Barcelona,
344            Barcelona,
345            Barcelona,
346    Valencia/València,
347                  Sant
348               Madrid,
349            Barcelona,
350               no_data
351               no_data
352               Madrid,
353                Palma,
354               Madrid,
355            Barcelona,
356                 Palma
357               Madrid,
358            Barcelona,
359               Pasaia,
360            Barcelona,
361            Barcelona,
362            Barcelona,
363             Marbella,
364            Barcelona,
365               Madrid,
366               Madrid,
367               Pozuelo
368            Barcelona,
369               Madrid,
370             Marbella,
371            Barcelona,
372            Barcelona,
373              Sevilla,
374               Madrid,
375            Barcelona,
376            Barcelona,
377            Cerdanyola
378            Barcelona,
379           Sarriguren,
380            Barcelona,
381               Madrid,
382            Barcelona,
383               no_data
384              Sevilla,
385            Barcelona,
386            Barcelona,
387              Sevilla,
388            Barcelona,
389            Salamanca,
390            Cerdanyola
391            Barcelona,
392              Cornellà
393            Barcelona,
394            Barcelona,
395               Madrid,
396     Alicante/Alacant,
397            Barcelona,
398                  Sant
399            Barcelona,
400            Tarragona,
401            Barcelona,
402               Málaga,
403            Barcelona,
404           Sarriguren,
405            Barcelona,
406     Alicante/Alacant,
407              Andorra,
408               Madrid,
409               Madrid,
410               Madrid,
411               Madrid,
412            Barcelona,
413               Madrid,
414              Cornellà
415            Barcelona,
416            Barcelona,
417               Madrid,
418            Cerdanyola
419                    La
420            Barcelona,
421            Barcelona,
422            Barcelona,
423            Barcelona,
424          Donostia-San
425            Barcelona,
426            Barcelona,
427               Madrid,
428                 Santa
429               Madrid,
430            Barcelona,
431                  Sant
432            Barcelona,
433                Caldes
434            Cerdanyola
435             Comunidad
436              Sevilla,
437            Barcelona,
438            Barcelona,
439    Valencia/València,
440            Barcelona,
441            Barcelona,
442            Barcelona,
443               Madrid,
444               Madrid,
445            Barcelona,
446            Barcelona,
447            Cerdanyola
448               Madrid,
449            Barcelona,
450            Barcelona,
451            Barcelona,
452            Barcelona,
453               Madrid,
454               Madrid,
455            Barcelona,
456              Sevilla,
457           Sarriguren,
458               Málaga,
459             Zaragoza,
460            Barcelona,
461               Madrid,
462     Alicante/Alacant,
463            Barcelona,
464              Cornellà
465                  Sant
466               Madrid,
467            Barcelona,
468            Tarragona,
469                  Sant
470            Barcelona,
471              Sevilla,
472            Cerdanyola
473            Barcelona,
474               Madrid,
475            Barcelona,
476               Málaga,
477               Madrid,
478              Cornellà
479            Barcelona,
480            Tarragona,
481            Barcelona,
482            Barcelona,
483            Cerdanyola
484            Barcelona,
485               Madrid,
486            Barcelona,
487               Madrid,
488               Málaga,
489            Barcelona,
490            Barcelona,
491            Barcelona,
492            Cerdanyola
493            Barcelona,
494           Sarriguren,
495            Barcelona,
496           Sarriguren,
497            Barcelona,
498            Barcelona,
499            Barcelona,
Name: Ubicación, dtype: object

In [ ]:
df_ds['Ubicación'] = df_ds['Ubicación'].str.split(' ').str[0]

In [ ]:
df_ds['Ubicación'] = df_ds['Ubicación'].str.replace(',', '')

#### Días activos:

In [234]:
df_ds['Días activos']

0            2 días
1          11 horas
2          1 semana
3          1 semana
4           7 horas
5           2 horas
6            4 días
7            4 días
8            3 días
9          1 semana
10        2 semanas
11         1 semana
12        3 semanas
13           2 días
14           4 días
15        3 semanas
16         1 semana
17        3 semanas
18        4 semanas
19        3 semanas
20         23 horas
21        3 semanas
22          3 horas
23         14 horas
24          3 meses
25         14 horas
26         1 semana
27         1 semana
28        3 semanas
29           3 días
30        3 semanas
31           4 días
32          5 horas
33           4 días
34           5 días
35        3 semanas
36         1 semana
37            1 día
38         1 semana
39           4 días
40         14 horas
41           5 días
42           5 días
43         14 horas
44         14 horas
45        2 semanas
46          no_data
47        3 semanas
48           3 días
49         1 semana
50           3 días
51        3 semanas
52            1 mes
53        3 semanas
54         1 semana
55           6 días
56        3 semanas
57           2 días
58         1 semana
59        3 semanas
60         14 horas
61           3 días
62        2 semanas
63           5 días
64            1 mes
65            1 día
66        2 semanas
67         1 semana
68            1 mes
69           6 días
70        2 semanas
71           4 días
72           1 hora
73           5 días
74            1 mes
75        3 semanas
76        2 semanas
77        2 semanas
78         1 semana
79          2 meses
80        2 semanas
81         1 semana
82           3 días
83          6 horas
84         1 semana
85         1 semana
86         19 horas
87         1 semana
88        4 semanas
89          no_data
90          5 meses
91            1 mes
92          2 meses
93            1 mes
94           3 días
95          2 meses
96        3 semanas
97         1 semana
98          4 meses
99         1 semana
100        1 semana
101        1 semana
102       2 semanas
103           1 mes
104         5 meses
105         2 meses
106           1 día
107        1 semana
108           1 mes
109          4 días
110       2 semanas
111       3 semanas
112          4 días
113           1 mes
114       2 semanas
115           1 día
116           1 día
117       2 semanas
118          5 días
119          2 días
120          6 días
121       2 semanas
122       2 semanas
123           1 mes
124          4 días
125          6 días
126        1 semana
127       3 semanas
128        14 horas
129       2 semanas
130         6 horas
131           1 día
132       2 semanas
133       2 semanas
134          3 días
135        1 semana
136        14 horas
137           1 mes
138          5 días
139        1 semana
140       3 semanas
141           1 mes
142        1 semana
143         3 meses
144        14 horas
145        1 semana
146        1 semana
147       2 semanas
148          6 días
149       3 semanas
150       2 semanas
151          5 días
152       2 semanas
153          3 días
154       2 semanas
155       3 semanas
156          5 días
157        1 semana
158          4 días
159       3 semanas
160        1 semana
161           1 mes
162        10 horas
163          4 días
164       2 semanas
165          4 días
166          4 días
167       3 semanas
168       2 semanas
169       3 semanas
170          6 días
171           1 día
172         2 meses
173           1 mes
174          6 días
175        1 semana
176        20 horas
177       2 semanas
178         3 meses
179        14 horas
180          4 días
181          3 días
182        1 semana
183        1 semana
184           1 mes
185       3 semanas
186          3 días
187       2 semanas
188         3 meses
189           1 mes
190        1 semana
191           1 mes
192          4 días
193       2 semanas
194       3 semanas
195        14 horas
196       4 semanas
197          3 días
198          6 días
199       3 semanas
200       3 semanas
201         no_data
202          4 días
203        1 semana
204       2 semanas
205          3 días
206        1 semana
207         2 meses
208        1 semana
209       4 semanas
210          4 días
211        1 semana
212       3 semanas
213          6 días
214        1 semana
215       3 semanas
216        1 semana
217         3 meses
218       3 semanas
219        1 semana
220        1 semana
221        1 semana
222       3 semanas
223         2 meses
224           1 día
225        1 semana
226          5 días
227          3 días
228        1 semana
229       3 semanas
230           1 mes
231       2 semanas
232          2 días
233          5 días
234           1 mes
235       3 semanas
236       3 semanas
237           1 mes
238        1 semana
239        1 semana
240          6 días
241          3 días
242       2 semanas
243         2 horas
244        1 semana
245          6 días
246           1 día
247          6 días
248          3 días
249       2 semanas
250         2 horas
251        1 semana
252          6 días
253           1 día
254       2 semanas
255        1 semana
256          3 días
257       3 semanas
258         4 meses
259        1 semana
260          6 días
261        1 semana
262       2 semanas
263      55 minutos
264        1 semana
265          6 días
266           1 mes
267        1 semana
268        1 semana
269       3 semanas
270     16 segundos
271       3 semanas
272        1 semana
273           1 día
274       3 semanas
275         no_data
276         2 horas
277           1 mes
278       3 semanas
279       2 semanas
280        1 semana
281        23 horas
282       3 semanas
283           1 mes
284          4 días
285         4 meses
286        1 semana
287       3 semanas
288          3 días
289           1 mes
290           1 mes
291          6 días
292       2 semanas
293        1 semana
294       4 semanas
295          2 días
296           1 mes
297         4 meses
298        1 semana
299       2 semanas
300        11 horas
301           1 mes
302        1 semana
303          3 días
304       3 semanas
305           1 mes
306           1 día
307           1 día
308        1 semana
309        1 semana
310        1 semana
311        1 semana
312          2 días
313          5 días
314      16 minutos
315       3 semanas
316       3 semanas
317          6 días
318        1 semana
319        1 semana
320        1 semana
321         3 meses
322       3 semanas
323           1 mes
324       3 semanas
325          3 días
326       3 semanas
327        1 semana
328         4 meses
329           1 mes
330         3 meses
331          3 días
332         2 meses
333       2 semanas
334       3 semanas
335       3 semanas
336          4 días
337          5 días
338        1 semana
339        1 semana
340           1 mes
341          3 días
342           1 mes
343          4 días
344        1 semana
345        15 horas
346         4 meses
347          4 días
348          1 hora
349       2 semanas
350         no_data
351         no_data
352        1 semana
353        11 horas
354       2 semanas
355       2 semanas
356       2 semanas
357          4 días
358           1 mes
359          4 días
360       2 semanas
361       2 semanas
362       2 semanas
363         4 horas
364        15 horas
365        1 semana
366          5 días
367       2 semanas
368          3 días
369        1 semana
370         4 horas
371       2 semanas
372          2 días
373          6 días
374         4 meses
375           1 día
376         4 meses
377        1 semana
378       2 semanas
379       3 semanas
380         4 meses
381           1 mes
382           1 mes
383         no_data
384           1 mes
385           1 mes
386        15 horas
387         2 meses
388          4 días
389          2 días
390        1 semana
391          3 días
392       3 semanas
393       2 semanas
394        1 semana
395           1 mes
396       2 semanas
397       2 semanas
398         3 meses
399          2 días
400          4 días
401       2 semanas
402       2 semanas
403       3 semanas
404          3 días
405        11 horas
406        1 semana
407          5 días
408          5 días
409        1 semana
410        15 horas
411          5 días
412       2 semanas
413        1 semana
414       3 semanas
415        1 semana
416           1 mes
417           1 mes
418        15 horas
419       2 semanas
420        1 semana
421           1 mes
422           1 mes
423         4 meses
424        1 semana
425        1 semana
426        14 horas
427        1 semana
428       2 semanas
429       2 semanas
430           1 mes
431           1 mes
432          5 días
433       3 semanas
434        1 semana
435       2 semanas
436         2 meses
437       2 semanas
438           1 mes
439         4 meses
440        1 semana
441       2 semanas
442       2 semanas
443          5 días
444        1 semana
445          5 días
446       3 semanas
447        15 horas
448           1 mes
449       2 semanas
450          5 días
451         2 meses
452         3 meses
453          5 días
454         2 meses
455        1 semana
456       2 semanas
457          3 días
458       3 semanas
459           1 mes
460       3 semanas
461       2 semanas
462           1 mes
463       2 semanas
464       3 semanas
465          4 días
466          3 días
467          6 días
468          6 días
469          6 días
470           1 mes
471         2 meses
472        1 semana
473           1 mes
474       2 semanas
475          5 días
476          5 días
477        1 semana
478       3 semanas
479       2 semanas
480          6 días
481           1 mes
482       3 semanas
483        1 semana
484          6 días
485           1 mes
486           1 mes
487        1 semana
488           1 mes
489       3 semanas
490       2 semanas
491           1 mes
492        1 semana
493        1 semana
494       2 semanas
495         3 meses
496          3 días
497        1 semana
498          3 días
499          2 días
Name: Días activos, dtype: object

In [ ]:
df_ds['Días activos'] = df_ds['Días activos'].str.replace('Publicado hace hace', '')

#### Solicitudes:

In [ ]:
lista_rem_so = [' visualizaciones', ' visualización', '.']

for i in lista_rem_so:
    df_ds['Nº Solicitudes'] = df_ds['Nº Solicitudes'].str.replace(i, '')

In [ ]:
df_ds['Nº Solicitudes'] = df_ds['Nº Solicitudes'].astype(int)

In [245]:
df_ds['Nº Solicitudes'].head()

0     749
1     180
2    2011
3     305
4     215
Name: Nº Solicitudes, dtype: int64

#### Nivel experiencia:

In [278]:
mask_ds_nexp = df_ds['Nivel experiencia'].str.contains('Sin experiencia|Algo de responsabilidad|Intermedio|Prácticas')

In [ ]:
df_ds.loc[-mask_ds_nexp,'Nivel experiencia'] = 'no_data'

#### Tipo jornada

In [331]:
df_ds['Tipo jornada'].unique()

array(['Jornada completa', 'Contrato por obra', 'Prácticas',
       'Contrato indefinido', 'Media jornada', 'no_data', 'Temporal'],
      dtype=object)

In [322]:
mask_tjor = df_ds['Tipo jornada'].str.contains('Servicio de información|Otro')

In [ ]:
df_ds.loc[-mask_tjor,'Tipo jornada'] = 'no_data'

#### Guardado del fichero limpio

In [337]:
df_ds.to_csv('info_data_scientist_clean.csv')

## Latitudes y longitudes

In [40]:
df_das = pd.read_csv('info_data_job_market_research_lat-lon.csv')

In [41]:
df_lonlat = pd.read_csv('listado-longitud-latitud-municipios-espana.csv', sep = ';')

In [50]:
df_lonlat

      Comunidad          Provincia  Población   Latitud    Longitud
0     Andalucía            Almería       Abla  37,14114   -2,780104
1     Andalucía            Almería   Abrucena  37,13305   -2,797098
2     Andalucía            Almería       Adra  36,74807   -3,022522
3     Andalucía            Almería  Albánchez   37,2871   -2,181163
4     Andalucía            Almería  Alboloduy  37,03319    -2,62175
...         ...                ...        ...       ...         ...
8107   Valencia  Valencia/València     Xeresa   39,0091  -0,2179918
8108   Valencia  Valencia/València  Xirivella  39,46669  -0,4277937
8109   Valencia  Valencia/València     Yátova    39,385   -0,808174
8110   Valencia  Valencia/València  Yesa (La)  39,49916   -0,426125
8111   Valencia  Valencia/València      Zarra  39,09138   -1,075068

[8112 rows x 5 columns]

In [51]:
map_jobs = pd.merge(df_das, df_lonlat, left_on = 'Ubicación', right_on = 'Población')

In [62]:
map_jobs.to_csv('map_jobs.csv')

In [59]:
map_jobs['lat'] = map_jobs['lat'].str.replace(',', '.')

In [60]:
map_jobs['lon'] = map_jobs['lon'].str.replace(',', '.')

In [61]:
map_jobs.head()

,Unnamed: 0,Nombre empresa,Puesto ofertado,Ubicación,Días activos,Nº Solicitudes,Nivel experiencia,Sector,Tipo jornada,Funciones laborales,Descripción,Tipo puesto,Comunidad,Provincia,Población,lat,lon
0,0,Amazon,Junior Data Analyst,Barcelona,6 horas,66,Sin experiencia,Software Servicios y tecnologías de la informa...,Jornada completa,Estrategia/planificación Análisis Tecnología d...,Description\n\nJunior Data Analyst\nWe are hir...,Data Analyst,Catalunya,Barcelona,Barcelona,41.38792,2.169919
1,4,YEGO,Junior Data Analyst,Barcelona,3 días,1122,Sin experiencia,Software Marketing y publicidad Transporte por...,Jornada completa,Ciencias Análisis Tecnología de la información,Mission\nAs a Junior Data Analyst you will sup...,Data Analyst,Catalunya,Barcelona,Barcelona,41.38792,2.169919
2,9,Adevinta,Data Analyst,Barcelona,6 días,666,Intermedio,Internet,Jornada completa,Ingeniería,Company Description\n\nWe are a world leading ...,Data Analyst,Catalunya,Barcelona,Barcelona,41.38792,2.169919
3,12,Bodas.net,Data Analyst,Barcelona,3 semanas,1097,Algo de responsabilidad,Internet,Jornada completa,Ingeniería Tecnología de la información,WHAT WE DO MATTERS:\n\nHere at Bodas.net (The ...,Data Analyst,Catalunya,Barcelona,Barcelona,41.38792,2.169919
4,15,Zurich Insurance Company Ltd,Data Analyst - Pricing,Barcelona,5 días,439,Intermedio,Seguros Servicios financieros,Jornada completa,Negocios,¿Qué buscamos?\n\nBuscamos un/a Data Analyst p...,Data Analyst,Catalunya,Barcelona,Barcelona,41.38792,2.169919

In [52]:
map_jobs.rename(columns = {'Latitud': 'lat', 'Longitud':'lon'}, inplace=True)
map_jobs

     Unnamed: 0                                     Nombre empresa  \
0             0                                             Amazon
1             4                                               YEGO
2             9                                           Adevinta
3            12                                          Bodas.net
4            15                       Zurich Insurance Company Ltd
5            17                                          Tech Data
6            21                                           Popcarte
7            22                                        Socialpoint
8            24                                         TravelPerk
9            25                                       Mur&Partners
10           31                                            Conexus
11           32                                             Akuaro
12           39                                     Walters People
13           40                                          Domestika
14           42                                             Criteo
15           43                                   Wallbox Chargers
16           46                                              Glovo
17           48                                     FTI Consulting
18           49                                           ZeptoLab
19           50                                            TeamCMP
20           54                                          Ingenuous
21           61                                             Preply
22           67                                             Veepee
23           68                                            PepsiCo
24           74                                               SQLI
25           75                                        Tripadvisor
26           77                                       ThoughtWorks
27           79                                            Scopely
28           81                                               Hays
29           82                    Barcelona Supercomputing Center
30           85                                          Xcelirate
31           87                                        Stayforlong
32           93                                GE Renewable Energy
33           95              Brico Depot Iberia (Grupo Kingfisher)
34          104                                                ALG
35          108                          Docler Holding Luxembourg
36          113        Penguin Random House Grupo Editorial, S.A.U
37          121                                             Colvin
38          124                                Wall Street English
39          128                                             Henkel
40          132                                     Page Personnel
41          133                                                JLL
42          134                                          Firmenich
43          137                                             Stuart
44          140                                           Exogroup
45          145                                            OPMjobs
46          147                                               King
47          149                                 ANCLA Headhunting+
48          150                                            Ubisoft
49          152                                            Landbot
50          158                                         Vistaprint
51          163                                          Tech Data
52          167                       Zurich Insurance Company Ltd
53          169                                            Conexus
54          171                               ElTenedor by TheFork
55          173                                           Kiwi.com
56          176                                            IWG plc
57          177                                      Blu Selection
58          181                                             Huxley
59          182                               Agilent Technologies
60          185                                             Criteo
61          186                                         Lionbridge
62          188               Universitat Pompeu Fabra - Barcelona
63          189                                         Tropicfeel
64          190                                              Glovo
65          192                                          papernest
66          193           Netcentric, A Cognizant Digital Business
67          194                                            albelli
68          195                                             Scal-e
69          205                                            Gartner
70          207                                             Preply
71          210                                    Novartis España
72          211                                          Domestika
73          214                                   FrieslandCampina
74          215                                     PPG Industries
75          216                                            Sunhero
76          218                                              Agoda
77          220                                       ThoughtWorks
78          223                    Barcelona Supercomputing Center
79          224             Tokio Marine HCC - International Group
80          226                                           Gameloft
81          227                                            TeamCMP
82          230                                           FREE NOW
83          231                                           Exoticca
84          232                                           NTT Ltd.
85          240                                           ZeptoLab
86          245                                            Scopely
87          247                                            Marfeel
88          251                                             Huxley
89          253                                       Ingram Micro
90          256                                         Vistaprint
91          257                                             Amazon
92          260                                               King
93          261                                             Altran
94          271                       Zurich Insurance Company Ltd
95          275                                                UPL
96          276                        Médicos Sin Fronteras (MSF)
97          277                                           Adevinta
98          279                                             Criteo
99          282                                          Xcelirate
100         283                                          Firmenich
101         284                                    Undefined Group
102         289                                              Glovo
103         290                                 Cobblestone Energy
104         293                                            Elastic
105         294                                    Novartis España
106         296                                       Jobandtalent
107         298                                             Preply
108         299                                      Blu Selection
109         300                                          Tech Data
110         301                                     PPG Industries
111         303                                            Conexus
112         304                                       Markem-Imaje
113         310                                         Vistaprint
114         311                                               Hays
115         312                                          Domestika
116         313                                             Veepee
117         316                                           Adevinta
118         322                                           GRUPO NS
119         324                    Barcelona Supercomputing Center
120         325               Universitat Pompeu Fabra - Barcelona
121         328                                           ZeptoLab
122         331                                          papernest
123         334                                           Adevinta
124         337                                             Amazon
125         338                                            TeamCMP
126         339                                         TravelPerk
127         343                                    Teleperformance
128         345                                    Teleperformance
129         348                                         Vistaprint
130         349           Netcentric, A Cognizant Digital Business
131         357                       Zurich Insurance Company Ltd
132         358                                              Glovo
133         360                                             Criteo
134         362                                            PepsiCo
135         363                                            Avanade
136         364                                          Tech Data
137         372                                     Rocket Digital
138         373                        Beckman Coulter Diagnostics
139         375                    Barcelona Supercomputing Center
140         378                                      Blu Selection
141         379                                            Ekkiden
142         383                                            OPMjobs
143         385                                             Ogilvy
144         389                                              Glovo
145         390                                            TeamCMP
146         391                                          Tech Data
147         394                                          Tech Data
148         395                                             Criteo
149         397                                           Adevinta
150         398                                              Agoda
151         402                                             everis
152         403                                     PPG Industries
153         404                                             Amazon
154         406                                          Tech Data
155         407                                            Avanade
156         409                                             Preply
157         410                                              IQVIA
158         411                                         Vistaprint
159         414                                          SEAT:CODE
160         417                                     PPG Industries
161         421                                            Avanade
162         422                                             everis
163         423                        Médicos Sin Fronteras (MSF)
164         424                                              Glovo
165         429                                             Criteo
166         431                                    Teleperformance
167         432                                           ZeptoLab
168         436                                          Domestika
169         437                                              Glovo
170         438                                     Page Personnel
171         441                                          Tech Data
172         443                                    Amazon.com, Inc
173         444                                              Agoda
174         445                                          Tech Data
175         446                                              Agoda
176         448                                         Vistaprint
177         449                                              IQVIA
178         450                                      Audalia Nexia
179         453                                          Tech Data
180         455                                              Glovo
181         456                                          Tech Data
182         459                                     Page Personnel
183         461                                              Agoda
184         462                                              Agoda
185         465                                   Accenture España
186         467                                              Agoda
187         468                                          Tech Data
188         470                                              Glovo
189         471                                   Accenture España
190         472                                   Accenture España
191         477                                              Glovo
192         478                                             Amazon
193         481                                              Glovo
194         482                                       Mur&Partners
195         484                                              Glovo
196         486                                              Glovo
197         488                                              Glovo
198         490                                          Tech Data
199         491                                              Agoda
200         492                                              Agoda
201         494                                              Glovo
202         495                                              Agoda
203         498                                          Tech Data
204         500                                             Amazon
205         501                       Zurich Insurance Company Ltd
206         503                                              WIRIS
207         506                                               YEGO
208         510                                          Koalaboox
209         517                                             Huxley
210         522                                     Stefanini EMEA
211         523                                         inITium HR
212         524                                         TravelPerk
213         529                                        Socialpoint
214         531                                     Gazelle Global
215         535                                   T-Systems Iberia
216         537                                              Glovo
217         538                                    Novartis España
218         540                                             Akuaro
219         544          Eurecat - Centro Tecnológico de Catalunya
220         547                                             Preply
221         549                                            Conexus
222         550                                         Chartboost
223         556                                               King
224         557                                            Harnham
225         559                                               ERNI
226         562                                    Gauss & Neumann
227         571                                           UserZoom
228         572                                         Rakuten TV
229         573                                           Adsmurai
230         577                                           Typeform
231         579                                     Page Personnel
232         590                                Skillsearch Limited
233         595                                             Madbox
234         602                                           Adevinta
235         603                                           Exoticca
236         604                                            XpertAI
237         608                                            Allianz
238         610                                             Metyis
239         613                                       Markem-Imaje
240         616                                     E-TIC Sistemes
241         617                                           ZeptoLab
242         618                                Entravision Digital
243         619                                       Platanomelón
244         621    Centro Nacional de Análisis Genómico (CNAG-CRG)
245         625                              BMAT Music Innovators
246         627                                             everis
247         631                                             Q-tech
248         638                                        Stayforlong
249         640                                          Firmenich
250         643                                            OPMjobs
251         644                                 Lectus Recruitment
252         646                                           ManoMano
253         648                              BMAT Music Innovators
254         656                                          benshi.ai
255         661                                Montreal Associates
256         663                                         Vistaprint
257         666                                     Hays Executive
258         667                                      MBN Solutions
259         669                                             Stuart
260         673                                          Dynatrace
261         676                                               Hach
262         677                                           Netquest
263         679                                        Ethikos 3.0
264         680                                       Activa Mutua
265         683                                            Brainly
266         686                                      Wind Mobility
267         687                    Barcelona Supercomputing Center
268         688                             Big Planet Recruitment
269         690                                        NEW WORK SE
270         691                                             Ogilvy
271         694                                       Jobandtalent
272         695          Eurecat - Centro Tecnológico de Catalunya
273         699                                BANDAI NAMCO Mobile
274         700                                             Preply
275         704                                   Accenture España
276         705                                            Elastic
277         706                                     eDreams ODIGEO
278         707                                   Qbeast Analytics
279         708                                          DataRobot
280         711                                            Scopely
281         713                                          Dow Jones
282         715       Medica Scientia Innovation Research (MEDSIR)
283         716                 Management Intelligence Consulting
284         717                                   Wallbox Chargers
285         720                                                DNV
286         723                                       PicsArt Inc.
287         724                       Zurich Insurance Company Ltd
288         732               Universitat Pompeu Fabra - Barcelona
289         737                                              Aizon
290         739                                          OLX Group
291         740                                           Typeform
292         741                                               King
293         742                                             Huxley
294         743                                            Webhelp
295         744                                        Tripadvisor
296         747                                           Typeform

In [37]:
map_jobs.head()

NameError: name 'maps_jobs' is not defined